### ISSUE TITLE
Cannot import previously exported feeds.

### ISSUE THREAD

**Issue by alatnet** [gandf/slick-rss#41]
Exported previous feeds to do a reinstall of the reader as apparently xkcd's feed were causing chunks of feeds to report that they had new items when they didnt.

Tried to import feeds back into the reader but getting error "No outline nodes of type 'rss' were found to import."

Steps to reproduce: export feeds, reinstall (remove then install from web store), import feeds.

Here's the previously exported feeds:
`<?xml version="1.0" encoding="ISO-8859-1"?><opml version="2.0"><head><title>Slick RSS OPML Export</title></head><body><outline type="rss" text="Sexless Friend" xmlUrl="http://www.mangahere.co/rss/sexless_friend.xml" group="" excludeUnreadCount=0/><outline type="rss" text="deviantART: gallery:meganekkochaser/37582820" xmlUrl="https://backend.deviantart.com/rss.xml?type=deviation&amp;q=by:meganekkochaser+sort:time+meta:all" group="" excludeUnreadCount=0/><outline type="rss" text="Comics – RandoWis" xmlUrl="http://randowis.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="kukuruyo" xmlUrl="http://kukuruyo.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Dude and Death : The Origins" xmlUrl="http://tapastic.com/rss/series/24884" group="" excludeUnreadCount=0/><outline type="rss" text="The Adventures of Business Cat" xmlUrl="http://www.businesscat.happyjar.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Dragon's Burn" xmlUrl="http://dragonsburn.tumblr.com/rss" group="" excludeUnreadCount=0/><outline type="rss" text="4-Panel Life" xmlUrl="http://tapastic.com/rss/series/6107" group="" excludeUnreadCount=0/><outline type="rss" text="The Escapist : Critical Miss" xmlUrl="https://www.escapistmagazine.com/v2/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="the GaMERCaT" xmlUrl="http://tapastic.com/rss/series/526" group="" excludeUnreadCount=0/><outline type="rss" text="Fisheye Placebo" xmlUrl="http://tapastic.com/rss/series/347" group="" excludeUnreadCount=0/><outline type="rss" text="deviantART: gallery:yuumei/42604730" xmlUrl="https://backend.deviantart.com/rss.xml?type=deviation&amp;q=by:yuumei+sort:time+meta:all" group="" excludeUnreadCount=0/><outline type="rss" text="SugarStars" xmlUrl="http://tapastic.com/rss/series/262" group="" excludeUnreadCount=0/><outline type="rss" text="Ribon" xmlUrl="http://tapastic.com/rss/series/313" group="" excludeUnreadCount=0/><outline type="rss" text="Megatokyo Comics" xmlUrl="http://megatokyo.com/rss/strips.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Charlie Sheen" xmlUrl="http://charliesheencomic.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="SPACE BASTARDS" xmlUrl="http://space-bastards.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Gone With the Blastwave" xmlUrl="http://www.blastwave-comic.com/rss/blastwave.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Super Effective" xmlUrl="http://www.vgcats.com/super/se.rdf.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Chaos Life" xmlUrl="http://chaoslife.findchaos.com/feed" group="" excludeUnreadCount=0/><outline type="rss" text="The GaMERCaT" xmlUrl="http://www.thegamercat.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="FindChaos" xmlUrl="http://www.findchaos.com/feed" group="" excludeUnreadCount=0/><outline type="rss" text="BladeKitten.com - Most Recent Blade Kitten Comics" xmlUrl="http://feeds2.feedburner.com/bladekittencomics" group="" excludeUnreadCount=0/><outline type="rss" text="Head Trip" xmlUrl="http://headtrip.keenspot.com/rss.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Ubunchu!" xmlUrl="http://divajutta.com/doctormo/ubunchu/feed.rss" group="" excludeUnreadCount=0/><outline type="rss" text="Ctrl+Alt+Del" xmlUrl="http://www.cad-comic.com/rss/rss.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Aki-chan's Life" xmlUrl="http://www.jimmys-desktop.de/aki.php?rss" group="" excludeUnreadCount=0/><outline type="rss" text="Manly Guys Doing Manly Things" xmlUrl="http://thepunchlineismachismo.com/feed" group="" excludeUnreadCount=0/><outline type="rss" text="EVA-303 Updates" xmlUrl="http://eva303.smackjeeves.com/rss/" group="" excludeUnreadCount=0/><outline type="rss" text="JESUS CHRIST - IN THE NAME OF THE GUN" xmlUrl="http://jesuschriststory.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="The Setup Wizard" xmlUrl="http://thesetupwizard.tumblr.com/rss" group="" excludeUnreadCount=0/><outline type="rss" text="Digimon World Re:Digitized Translation" xmlUrl="https://digimonworldre.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="The World" xmlUrl="http://www.coldbird.net/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="DevZone Topic Subscriptions" xmlUrl="https://devtalk.nvidia.com/rss/feed/tL%2FrW%2BdWpEX7UHUtLNDPsKmaQKaSP6w8udKaQLjmk0A%3D" group="" excludeUnreadCount=0/><outline type="rss" text="Did You Know Gaming?" xmlUrl="http://didyouknowgaming.com/rss" group="" excludeUnreadCount=0/><outline type="rss" text="PSO-World.com - The World's Largest Phantasy Star Community - PS Universe, Portable, Zero, Online" xmlUrl="http://www.pso-world.com/rss.xml" group="" excludeUnreadCount=0/><outline type="rss" text="Break The Bank Habit" xmlUrl="http://brightstarcu.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Vocaloidism" xmlUrl="http://www.vocaloidism.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="PSO2 NA Blog" xmlUrl="http://bumped.org/pso2na/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Phantasy Star Fan Blog" xmlUrl="http://www.bumped.org/psublog/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Xenoaisam Website" xmlUrl="http://xenoaisam.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Mary Cagle Let's Speak English" xmlUrl="http://www.marycagle.com/rss.php" group="" excludeUnreadCount=0/><outline type="rss" text="Isekai Soul-Cyborg Translations » Feed" xmlUrl="https://isekaicyborg.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="The Hazards of Being a Main Character" xmlUrl="https://tapastic.com/rss/series/12603" group="" excludeUnreadCount=0/><outline type="rss" text="Please Be Merciful" xmlUrl="https://tapastic.com/rss/series/42550" group="" excludeUnreadCount=0/><outline type="rss" text="The Gamer" xmlUrl="https://www.webtoons.com/en/action/the-gamer/rss?title_no=88" group="" excludeUnreadCount=0/><outline type="rss" text="The Pigeon Gazette" xmlUrl="https://tapas.io/rss/series/8207" group="" excludeUnreadCount=0/><outline type="rss" text="Genjicat" xmlUrl="https://tapas.io/rss/series/68320" group="" excludeUnreadCount=0/><outline type="rss" text="mikiko mini comics" xmlUrl="https://tapas.io/rss/series/4668" group="" excludeUnreadCount=0/><outline type="rss" text="Soggy Cardboard" xmlUrl="http://www.soggycardboard.com/?feed=rss2" group="" excludeUnreadCount=0/><outline type="rss" text="Surfacage [and the world will turn to ash]" xmlUrl="http://www.surfacage.net/rss" group="" excludeUnreadCount=0/><outline type="rss" text="DBZ - The Girl Next Door" xmlUrl="http://the-girl-next-door.smackjeeves.com/rss/" group="" excludeUnreadCount=0/><outline type="rss" text="Erma" xmlUrl="https://tapas.io/rss/series/23931" group="" excludeUnreadCount=0/><outline type="rss" text="Watashu" xmlUrl="https://tapas.io/rss/series/33746" group="" excludeUnreadCount=0/><outline type="rss" text="Coon Comic" xmlUrl="https://tapas.io/rss/series/53898" group="" excludeUnreadCount=0/><outline type="rss" text="Customer Service Wolf" xmlUrl="http://customerservicewolf.com/rss" group="" excludeUnreadCount=0/><outline type="rss" text="Crawling Dreams" xmlUrl="https://tapas.io/rss/series/91644" group="" excludeUnreadCount=0/><outline type="rss" text="The Crawling City" xmlUrl="https://tapas.io/rss/series/42485" group="" excludeUnreadCount=0/><outline type="rss" text="The Elf is a Freeloader" xmlUrl="https://www.euricette.com/category/series/the-elf-is-a-freeloader/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="dijoninpieces" xmlUrl="https://dijoninpieces.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Omega Harem Translations » Feed" xmlUrl="https://omegaharem.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Fmgandalf translations » Feed" xmlUrl="https://fmgandalf.wordpress.com/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="dijoninpieces » I Was a Sword When I Reincarnated Category Feed" xmlUrl="https://dijoninpieces.wordpress.com/category/i-was-a-sword-when-i-reincarnated/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="“A Tale of Two Rulers”" xmlUrl="http://figmentforms.tumblr.com/rss" group="" excludeUnreadCount=0/><outline type="rss" text="Haruka" xmlUrl="https://www.webtoons.com/en/challenge/haruka/rss?title_no=141998" group="" excludeUnreadCount=0/><outline type="rss" text="Reincarnated As A Dragons Egg" xmlUrl="https://dsrealmtranslations.com/category/reincarnated-as-a-dragons-egg/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="Negative Frames" xmlUrl="https://tapas.io/rss/series/88299" group="" excludeUnreadCount=0/><outline type="rss" text="Stalker x Stalker" xmlUrl="https://www.webtoons.com/en/challenge/stalker-x-stalker/rss?title_no=245662" group="" excludeUnreadCount=0/><outline type="rss" text="Future Sound" xmlUrl="https://tapas.io/rss/series/124387" group="" excludeUnreadCount=0/><outline type="rss" text="Edd Lai's Stories" xmlUrl="https://www.webtoons.com/en/challenge/edd-lais-stories/rss?title_no=301213" group="" excludeUnreadCount=0/><outline type="rss" text="Deathsitter" xmlUrl="https://www.webtoons.com/en/challenge/deathsitter/rss?title_no=293285" group="" excludeUnreadCount=0/><outline type="rss" text="London Vampire" xmlUrl="https://www.webtoons.com/en/challenge/london-vampire/rss?title_no=70817" group="" excludeUnreadCount=0/><outline type="rss" text="Magnolia Online" xmlUrl="https://www.webtoons.com/en/challenge/magnolia-online/rss?title_no=56485" group="" excludeUnreadCount=0/><outline type="rss" text="Clinic of Horrors" xmlUrl="https://www.webtoons.com/en/challenge/clinic-of-horrors/rss?title_no=274661" group="" excludeUnreadCount=0/><outline type="rss" text="My Succubus Girlfriend" xmlUrl="https://www.webtoons.com/en/challenge/my-succubus-girlfriend/rss?title_no=116486" group="" excludeUnreadCount=0/><outline type="rss" text="Vampire Gamer" xmlUrl="https://www.webtoons.com/en/challenge/vampire-gamer/rss?title_no=388506" group="" excludeUnreadCount=0/><outline type="rss" text="system32comics" xmlUrl="https://www.webtoons.com/en/challenge/system32comics/rss?title_no=235074" group="" excludeUnreadCount=0/><outline type="rss" text="The Bikini Bottom Horror" xmlUrl="https://stillinthesimulation.com/untitled-comic/feed/" group="" excludeUnreadCount=0/><outline type="rss" text="My Girlfriend's a Hex Maniac" xmlUrl="https://tapas.io/rss/series/124936" group="" excludeUnreadCount=0/><outline type="rss" text="Little Things PH" xmlUrl="https://tapas.io/rss/series/19771" group="" excludeUnreadCount=0/><outline type="rss" text="Dungeons &amp; Doodles: Tales from the Tables" xmlUrl="https://tapas.io/rss/series/212513" group="" excludeUnreadCount=0/><outline type="rss" text="The Weekly Roll" xmlUrl="https://www.webtoons.com/en/challenge/the-weekly-roll/rss?title_no=358889" group="" excludeUnreadCount=0/><outline type="rss" text="Lore Olympus" xmlUrl="https://www.webtoons.com/en/romance/lore-olympus/rss?title_no=1320" group="" excludeUnreadCount=0/><outline type="rss" text="Clinic of Horrors (Webtoon Originals)" xmlUrl="https://www.webtoons.com/en/supernatural/clinic-of-horrors/rss?title_no=3414" group="" excludeUnreadCount=0/><outline type="rss" text="The Magineer" xmlUrl="https://www.themagineer.com/rss/" group="" excludeUnreadCount=0/></body></opml>`

**Comment by gandf** [comment]
Hi,

Last version has several issues. Some of these issues are fixed.
Commit [de32864](https://github.com/gandf/slick-rss/commit/de328649e32f82d4f4bf522618f7a529649b6ede) fix #35 (Import/Export not work).
Commit [00b1635](https://github.com/gandf/slick-rss/commit/00b1635d1dd5ca59455922621ef66e40a99f230a) fix Fix add feed (order and exclude).

I think you have try to import because of feeds malfunction.
Version 3.5.1 should fix all these issues.

#https://github.com/gandf/slick-rss/discussions/34

Tuesday evening I released a 3.5.1 version which will fix this issue and should fix bigger issues.
I hope it will be published no later than Friday.

If you want to fix your file, replace all 'excludeUnreadCount=0' by 'excludeUnreadCount="0"'

Your file fixed but you have to wait for version 3.5.1 to import it:

`<?xml version="1.0" encoding="ISO-8859-1"?><opml version="2.0"><head><title>Slick RSS OPML Export</title></head><body><outline type="rss" text="Sexless Friend" xmlUrl="http://www.mangahere.co/rss/sexless_friend.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="deviantART: gallery:meganekkochaser/37582820" xmlUrl="https://backend.deviantart.com/rss.xml?type=deviation&amp;q=by:meganekkochaser+sort:time+meta:all" group="" excludeUnreadCount="0"/><outline type="rss" text="Comics – RandoWis" xmlUrl="http://randowis.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="kukuruyo" xmlUrl="http://kukuruyo.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Dude and Death : The Origins" xmlUrl="http://tapastic.com/rss/series/24884" group="" excludeUnreadCount="0"/><outline type="rss" text="The Adventures of Business Cat" xmlUrl="http://www.businesscat.happyjar.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Dragon's Burn" xmlUrl="http://dragonsburn.tumblr.com/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="4-Panel Life" xmlUrl="http://tapastic.com/rss/series/6107" group="" excludeUnreadCount="0"/><outline type="rss" text="The Escapist : Critical Miss" xmlUrl="https://www.escapistmagazine.com/v2/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="the GaMERCaT" xmlUrl="http://tapastic.com/rss/series/526" group="" excludeUnreadCount="0"/><outline type="rss" text="Fisheye Placebo" xmlUrl="http://tapastic.com/rss/series/347" group="" excludeUnreadCount="0"/><outline type="rss" text="deviantART: gallery:yuumei/42604730" xmlUrl="https://backend.deviantart.com/rss.xml?type=deviation&amp;q=by:yuumei+sort:time+meta:all" group="" excludeUnreadCount="0"/><outline type="rss" text="SugarStars" xmlUrl="http://tapastic.com/rss/series/262" group="" excludeUnreadCount="0"/><outline type="rss" text="Ribon" xmlUrl="http://tapastic.com/rss/series/313" group="" excludeUnreadCount="0"/><outline type="rss" text="Megatokyo Comics" xmlUrl="http://megatokyo.com/rss/strips.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Charlie Sheen" xmlUrl="http://charliesheencomic.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="SPACE BASTARDS" xmlUrl="http://space-bastards.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Gone With the Blastwave" xmlUrl="http://www.blastwave-comic.com/rss/blastwave.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Super Effective" xmlUrl="http://www.vgcats.com/super/se.rdf.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Chaos Life" xmlUrl="http://chaoslife.findchaos.com/feed" group="" excludeUnreadCount="0"/><outline type="rss" text="The GaMERCaT" xmlUrl="http://www.thegamercat.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="FindChaos" xmlUrl="http://www.findchaos.com/feed" group="" excludeUnreadCount="0"/><outline type="rss" text="BladeKitten.com - Most Recent Blade Kitten Comics" xmlUrl="http://feeds2.feedburner.com/bladekittencomics" group="" excludeUnreadCount="0"/><outline type="rss" text="Head Trip" xmlUrl="http://headtrip.keenspot.com/rss.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Ubunchu!" xmlUrl="http://divajutta.com/doctormo/ubunchu/feed.rss" group="" excludeUnreadCount="0"/><outline type="rss" text="Ctrl+Alt+Del" xmlUrl="http://www.cad-comic.com/rss/rss.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Aki-chan's Life" xmlUrl="http://www.jimmys-desktop.de/aki.php?rss" group="" excludeUnreadCount="0"/><outline type="rss" text="Manly Guys Doing Manly Things" xmlUrl="http://thepunchlineismachismo.com/feed" group="" excludeUnreadCount="0"/><outline type="rss" text="EVA-303 Updates" xmlUrl="http://eva303.smackjeeves.com/rss/" group="" excludeUnreadCount="0"/><outline type="rss" text="JESUS CHRIST - IN THE NAME OF THE GUN" xmlUrl="http://jesuschriststory.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="The Setup Wizard" xmlUrl="http://thesetupwizard.tumblr.com/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="Digimon World Re:Digitized Translation" xmlUrl="https://digimonworldre.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="The World" xmlUrl="http://www.coldbird.net/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="DevZone Topic Subscriptions" xmlUrl="https://devtalk.nvidia.com/rss/feed/tL%2FrW%2BdWpEX7UHUtLNDPsKmaQKaSP6w8udKaQLjmk0A%3D" group="" excludeUnreadCount="0"/><outline type="rss" text="Did You Know Gaming?" xmlUrl="http://didyouknowgaming.com/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="PSO-World.com - The World's Largest Phantasy Star Community - PS Universe, Portable, Zero, Online" xmlUrl="http://www.pso-world.com/rss.xml" group="" excludeUnreadCount="0"/><outline type="rss" text="Break The Bank Habit" xmlUrl="http://brightstarcu.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Vocaloidism" xmlUrl="http://www.vocaloidism.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="PSO2 NA Blog" xmlUrl="http://bumped.org/pso2na/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Phantasy Star Fan Blog" xmlUrl="http://www.bumped.org/psublog/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Xenoaisam Website" xmlUrl="http://xenoaisam.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Mary Cagle Let's Speak English" xmlUrl="http://www.marycagle.com/rss.php" group="" excludeUnreadCount="0"/><outline type="rss" text="Isekai Soul-Cyborg Translations » Feed" xmlUrl="https://isekaicyborg.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="The Hazards of Being a Main Character" xmlUrl="https://tapastic.com/rss/series/12603" group="" excludeUnreadCount="0"/><outline type="rss" text="Please Be Merciful" xmlUrl="https://tapastic.com/rss/series/42550" group="" excludeUnreadCount="0"/><outline type="rss" text="The Gamer" xmlUrl="https://www.webtoons.com/en/action/the-gamer/rss?title_no=88" group="" excludeUnreadCount="0"/><outline type="rss" text="The Pigeon Gazette" xmlUrl="https://tapas.io/rss/series/8207" group="" excludeUnreadCount="0"/><outline type="rss" text="Genjicat" xmlUrl="https://tapas.io/rss/series/68320" group="" excludeUnreadCount="0"/><outline type="rss" text="mikiko mini comics" xmlUrl="https://tapas.io/rss/series/4668" group="" excludeUnreadCount="0"/><outline type="rss" text="Soggy Cardboard" xmlUrl="http://www.soggycardboard.com/?feed=rss2" group="" excludeUnreadCount="0"/><outline type="rss" text="Surfacage [and the world will turn to ash]" xmlUrl="http://www.surfacage.net/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="DBZ - The Girl Next Door" xmlUrl="http://the-girl-next-door.smackjeeves.com/rss/" group="" excludeUnreadCount="0"/><outline type="rss" text="Erma" xmlUrl="https://tapas.io/rss/series/23931" group="" excludeUnreadCount="0"/><outline type="rss" text="Watashu" xmlUrl="https://tapas.io/rss/series/33746" group="" excludeUnreadCount="0"/><outline type="rss" text="Coon Comic" xmlUrl="https://tapas.io/rss/series/53898" group="" excludeUnreadCount="0"/><outline type="rss" text="Customer Service Wolf" xmlUrl="http://customerservicewolf.com/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="Crawling Dreams" xmlUrl="https://tapas.io/rss/series/91644" group="" excludeUnreadCount="0"/><outline type="rss" text="The Crawling City" xmlUrl="https://tapas.io/rss/series/42485" group="" excludeUnreadCount="0"/><outline type="rss" text="The Elf is a Freeloader" xmlUrl="https://www.euricette.com/category/series/the-elf-is-a-freeloader/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="dijoninpieces" xmlUrl="https://dijoninpieces.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Omega Harem Translations » Feed" xmlUrl="https://omegaharem.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Fmgandalf translations » Feed" xmlUrl="https://fmgandalf.wordpress.com/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="dijoninpieces » I Was a Sword When I Reincarnated Category Feed" xmlUrl="https://dijoninpieces.wordpress.com/category/i-was-a-sword-when-i-reincarnated/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="“A Tale of Two Rulers”" xmlUrl="http://figmentforms.tumblr.com/rss" group="" excludeUnreadCount="0"/><outline type="rss" text="Haruka" xmlUrl="https://www.webtoons.com/en/challenge/haruka/rss?title_no=141998" group="" excludeUnreadCount="0"/><outline type="rss" text="Reincarnated As A Dragons Egg" xmlUrl="https://dsrealmtranslations.com/category/reincarnated-as-a-dragons-egg/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="Negative Frames" xmlUrl="https://tapas.io/rss/series/88299" group="" excludeUnreadCount="0"/><outline type="rss" text="Stalker x Stalker" xmlUrl="https://www.webtoons.com/en/challenge/stalker-x-stalker/rss?title_no=245662" group="" excludeUnreadCount="0"/><outline type="rss" text="Future Sound" xmlUrl="https://tapas.io/rss/series/124387" group="" excludeUnreadCount="0"/><outline type="rss" text="Edd Lai's Stories" xmlUrl="https://www.webtoons.com/en/challenge/edd-lais-stories/rss?title_no=301213" group="" excludeUnreadCount="0"/><outline type="rss" text="Deathsitter" xmlUrl="https://www.webtoons.com/en/challenge/deathsitter/rss?title_no=293285" group="" excludeUnreadCount="0"/><outline type="rss" text="London Vampire" xmlUrl="https://www.webtoons.com/en/challenge/london-vampire/rss?title_no=70817" group="" excludeUnreadCount="0"/><outline type="rss" text="Magnolia Online" xmlUrl="https://www.webtoons.com/en/challenge/magnolia-online/rss?title_no=56485" group="" excludeUnreadCount="0"/><outline type="rss" text="Clinic of Horrors" xmlUrl="https://www.webtoons.com/en/challenge/clinic-of-horrors/rss?title_no=274661" group="" excludeUnreadCount="0"/><outline type="rss" text="My Succubus Girlfriend" xmlUrl="https://www.webtoons.com/en/challenge/my-succubus-girlfriend/rss?title_no=116486" group="" excludeUnreadCount="0"/><outline type="rss" text="Vampire Gamer" xmlUrl="https://www.webtoons.com/en/challenge/vampire-gamer/rss?title_no=388506" group="" excludeUnreadCount="0"/><outline type="rss" text="system32comics" xmlUrl="https://www.webtoons.com/en/challenge/system32comics/rss?title_no=235074" group="" excludeUnreadCount="0"/><outline type="rss" text="The Bikini Bottom Horror" xmlUrl="https://stillinthesimulation.com/untitled-comic/feed/" group="" excludeUnreadCount="0"/><outline type="rss" text="My Girlfriend's a Hex Maniac" xmlUrl="https://tapas.io/rss/series/124936" group="" excludeUnreadCount="0"/><outline type="rss" text="Little Things PH" xmlUrl="https://tapas.io/rss/series/19771" group="" excludeUnreadCount="0"/><outline type="rss" text="Dungeons &amp; Doodles: Tales from the Tables" xmlUrl="https://tapas.io/rss/series/212513" group="" excludeUnreadCount="0"/><outline type="rss" text="The Weekly Roll" xmlUrl="https://www.webtoons.com/en/challenge/the-weekly-roll/rss?title_no=358889" group="" excludeUnreadCount="0"/><outline type="rss" text="Lore Olympus" xmlUrl="https://www.webtoons.com/en/romance/lore-olympus/rss?title_no=1320" group="" excludeUnreadCount="0"/><outline type="rss" text="Clinic of Horrors (Webtoon Originals)" xmlUrl="https://www.webtoons.com/en/supernatural/clinic-of-horrors/rss?title_no=3414" group="" excludeUnreadCount="0"/><outline type="rss" text="The Magineer" xmlUrl="https://www.themagineer.com/rss/" group="" excludeUnreadCount="0"/></body></opml>`

**Comment by gandf** [comment]
New version 3.5.1 is published. Are you still having problems?
I just tested import of these feeds works on my Chrome browser. (I have not tested on vivaldi.)

Do you still have these problems with this new version?

**Comment by gandf** [comment]
These feeds imported but I can't see item (loading continuously).

**Comment by gandf** [comment]
Version 3.5.2 has just been released. It will allow these feeds to be read completely.
I think that version will arrive no later than Tuesday.
